name: audioplayers_example
description: This is an audioplayers example to test Flutter Web

version: 0.1.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  audioplayers:
    path: ../audioplayers
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false
